/*
 * This file is generated by jOOQ.
 */
package com.silesta.models;


import com.silesta.models.tables.BankOperations;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bank_operations</code>.
     */
    public static final BankOperations BANK_OPERATIONS = com.silesta.models.tables.BankOperations.BANK_OPERATIONS;
}
