/*
 * This file is generated by jOOQ.
 */
package com.silesta.models.tables.records;


import com.silesta.models.tables.BankOperations;

import java.sql.Date;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankOperationsRecord extends UpdatableRecordImpl<BankOperationsRecord> implements Record8<Float, String, Long, String, Boolean, Integer, Date, String> {

    private static final long serialVersionUID = 1629442007;

    /**
     * Setter for <code>public.bank_operations.amount</code>.
     */
    public void setAmount(Float value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bank_operations.amount</code>.
     */
    public Float getAmount() {
        return (Float) get(0);
    }

    /**
     * Setter for <code>public.bank_operations.desc</code>.
     */
    public void setDesc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bank_operations.desc</code>.
     */
    public String getDesc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bank_operations.ext_cat_id</code>.
     */
    public void setExtCatId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bank_operations.ext_cat_id</code>.
     */
    public Long getExtCatId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.bank_operations.cat_name</code>.
     */
    public void setCatName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bank_operations.cat_name</code>.
     */
    public String getCatName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bank_operations.is_income</code>.
     */
    public void setIsIncome(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bank_operations.is_income</code>.
     */
    public Boolean getIsIncome() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.bank_operations.id</code>.
     */
    public void setId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bank_operations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.bank_operations.op_date</code>.
     */
    public void setOpDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bank_operations.op_date</code>.
     */
    public Date getOpDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>public.bank_operations.source</code>.
     */
    public void setSource(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.bank_operations.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Float, String, Long, String, Boolean, Integer, Date, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Float, String, Long, String, Boolean, Integer, Date, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field1() {
        return BankOperations.BANK_OPERATIONS.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BankOperations.BANK_OPERATIONS.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BankOperations.BANK_OPERATIONS.EXT_CAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BankOperations.BANK_OPERATIONS.CAT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return BankOperations.BANK_OPERATIONS.IS_INCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BankOperations.BANK_OPERATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return BankOperations.BANK_OPERATIONS.OP_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BankOperations.BANK_OPERATIONS.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component1() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getExtCatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getOpDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value1() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getExtCatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCatName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getOpDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value1(Float value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value2(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value3(Long value) {
        setExtCatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value4(String value) {
        setCatName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value5(Boolean value) {
        setIsIncome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value6(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value7(Date value) {
        setOpDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord value8(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankOperationsRecord values(Float value1, String value2, Long value3, String value4, Boolean value5, Integer value6, Date value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankOperationsRecord
     */
    public BankOperationsRecord() {
        super(BankOperations.BANK_OPERATIONS);
    }

    /**
     * Create a detached, initialised BankOperationsRecord
     */
    public BankOperationsRecord(Float amount, String desc, Long extCatId, String catName, Boolean isIncome, Integer id, Date opDate, String source) {
        super(BankOperations.BANK_OPERATIONS);

        set(0, amount);
        set(1, desc);
        set(2, extCatId);
        set(3, catName);
        set(4, isIncome);
        set(5, id);
        set(6, opDate);
        set(7, source);
    }
}
